import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
        className="max-w-300 mx-auto py-24 min-h-full flex flex-col bg-white text-slate-900 dark:bg-slate-900 dark:text-white transition-colors duration-300"
      >
        <nav>
          <ul className="flex gap-5">
            <li className="bg-black text-white hover:text-yellow-500 px-3 py-1 rounded-lg">
              <Link href="/">
                Home
              </Link>
            </li>
            <li className="bg-black text-white hover:text-yellow-500 px-3 py-1 rounded-lg">
              <Link href="/about">
                About
              </Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
